services:
  postgres:
    image: 'postgres:15.3'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_SALES_DB}'
    ports:
      - '${POSTGRES_LOCAL_PORT}:${POSTGRES_CONTAINER_PORT}'
    labels:
      org.springframework.boot.jdbc.parameters: 'ssl=true&sslmode=require'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

volumes:
    postgres-data:
